//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace book_store
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int order_no { get; set; }
        public string user_name { get; set; }
        public Nullable<int> book_id { get; set; }
    
        public virtual book book { get; set; }
        public virtual userdata userdata { get; set; }
    }
}
